/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.idelogix.login.ui;

import com.idelogix.login.service.Globals;
import com.idelogix.login.service.Props;
import com.idelogix.login.service.UserService;
import com.idelogix.login.service.Utils;
import java.awt.Component;
import java.awt.event.WindowEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class LoginUI extends javax.swing.JFrame {

    private final Props props = Props.getInstance();

    /**
     * Creates new form MainUI
     */
    public LoginUI() {
        initComponents();
        myInitComponents();
    }

    private void myInitComponents() {
        //Allow OK button with enter
        clearValues();
        UIUtils.getLocalText(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHeading = new javax.swing.JLabel();
        pInfo = new javax.swing.JPanel();
        lEnterInfo = new javax.swing.JLabel();
        lUserName = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        bOK = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tUserName = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();
        cbRoles = new javax.swing.JComboBox<>();
        lSelectRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        lHeading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lHeading.setText("_Application_name");

        pInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lEnterInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lEnterInfo.setText("_Enter_requested_information");

        lUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lUserName.setText("_Name");

        lPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lPassword.setText("_Password");

        bOK.setText("_OK");
        bOK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bOKFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bOKFocusLost(evt);
            }
        });
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        bCancel.setText("_Cancel");
        bCancel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bCancelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bCancelFocusLost(evt);
            }
        });
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        tUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tUserNameFocusLost(evt);
            }
        });

        tPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tPasswordFocusGained(evt);
            }
        });

        cbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lSelectRole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSelectRole.setText("_Select_role");

        javax.swing.GroupLayout pInfoLayout = new javax.swing.GroupLayout(pInfo);
        pInfo.setLayout(pInfoLayout);
        pInfoLayout.setHorizontalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lEnterInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lUserName)
                                    .addComponent(lSelectRole))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbRoles, 0, 225, Short.MAX_VALUE)
                                    .addComponent(tUserName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                                .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                                .addComponent(lPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pInfoLayout.setVerticalGroup(
            pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEnterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUserName)
                    .addComponent(tUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSelectRole))
                .addGap(18, 18, 18)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPassword))
                .addGap(14, 14, 14)
                .addGroup(pInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancel)
                    .addComponent(bOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lHeading, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lHeading.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        String thePassword = new String(tPassword.getPassword());

        if (Utils.isUNameValid(tUserName.getText()) //Checks user name min lenght
                && Utils.isPwdValid(thePassword) //Checks password min lenght
                && UserService.getInstance().validateUserLogin(tUserName.getText(), thePassword, (String) cbRoles.getSelectedItem())) {
            //Logged successfuly
            this.setVisible(false);
            MainUI m = new MainUI();
            //Welcome message on info panel.
            m.setInfoText(Props.getInstance().getTxtProps("msg._Welcome") + " " + Globals.getLoggedUserName() + "!");
            //Make sure window is shown on same screen as loging dialog.
            m.setLocationRelativeTo(SwingUtilities.getWindowAncestor((Component) evt.getSource()));
            m.setVisible(true);
            //System.out.println(new UserService().getInstance().getAppUser());
        } else {
            tPassword.setText("");
            JOptionPane.showMessageDialog(this, UIUtils.getLocalText("msg._Wrong_password_or_user_name"));
        }
    }//GEN-LAST:event_bOKActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelActionPerformed

    private void tPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tPasswordFocusGained
  
    }//GEN-LAST:event_tPasswordFocusGained

    private void tUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tUserNameFocusLost
        fillRolesComboBox();
    }//GEN-LAST:event_tUserNameFocusLost

    private void bOKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bOKFocusGained
        this.getRootPane().setDefaultButton(bOK); // Allow Enter
    }//GEN-LAST:event_bOKFocusGained

    private void bCancelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bCancelFocusGained
        this.getRootPane().setDefaultButton(bCancel);
    }//GEN-LAST:event_bCancelFocusGained

    private void bOKFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bOKFocusLost
        this.getRootPane().setDefaultButton(null);
    }//GEN-LAST:event_bOKFocusLost

    private void bCancelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bCancelFocusLost
        this.getRootPane().setDefaultButton(null);
    }//GEN-LAST:event_bCancelFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOK;
    private javax.swing.JComboBox<String> cbRoles;
    private javax.swing.JLabel lEnterInfo;
    private javax.swing.JLabel lHeading;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lSelectRole;
    private javax.swing.JLabel lUserName;
    private javax.swing.JPanel pInfo;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUserName;
    // End of variables declaration//GEN-END:variables

    private void clearValues() {
        tUserName.setText("");
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(new String[0]);
        cbRoles.setModel(model);
        tPassword.setText("");
    }

    private void fillRolesComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(new String[0]);
        cbRoles.setModel(model);
        if (!tUserName.getText().equals("")) {
            if (UserService.getInstance().userExists(tUserName.getText())) {
                String[] arr = UserService.getInstance().getUserRoleList(tUserName.getText());
                if (!(arr.length==0)) {
                    model = new DefaultComboBoxModel<>(arr);
                    cbRoles.setModel(model);
                }
            }
        }

    }
}
