/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.idelogix.login.ui;

/**
 *
 * @author Administrator
 */
public class PasswordUI extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public PasswordUI() {
        initComponents();
        //Password
        //this.bPassword.setText(Props.getInstance().getTxtProps("button.bPassword"));
        //this.bChangePasswordYes.setText(Props.getInstance().getTxtProps("button.bChangePasswordYes"));
        //this.bChangePasswordNo.setText(Props.getInstance().getTxtProps("button.bChangePasswordNo"));
        //this.lOldPassword.setText(Props.getInstance().getTxtProps("label.lOldPassword"));
        //this.lNewPassword.setText(Props.getInstance().getTxtProps("label.lNewPassword"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pChangePassword = new javax.swing.JPanel();
        bChangePasswordYes = new javax.swing.JButton();
        lOldPassword = new javax.swing.JLabel();
        lNewPassword = new javax.swing.JLabel();
        bChangePasswordNo = new javax.swing.JButton();
        pfOldPassword = new javax.swing.JPasswordField();
        pfNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pChangePassword.setBackground(new java.awt.Color(255, 204, 204));

        bChangePasswordYes.setText("_Change");
        bChangePasswordYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangePasswordYesActionPerformed(evt);
            }
        });

        lOldPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lOldPassword.setText("_Old password");

        lNewPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lNewPassword.setText("_New password");

        bChangePasswordNo.setText("_Cancel");
        bChangePasswordNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangePasswordNoActionPerformed(evt);
            }
        });

        pfOldPassword.setText("jPasswordField1");

        pfNewPassword.setText("jPasswordField2");

        javax.swing.GroupLayout pChangePasswordLayout = new javax.swing.GroupLayout(pChangePassword);
        pChangePassword.setLayout(pChangePasswordLayout);
        pChangePasswordLayout.setHorizontalGroup(
            pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChangePasswordLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pChangePasswordLayout.createSequentialGroup()
                        .addGroup(pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lOldPassword))
                        .addGap(18, 18, 18)
                        .addGroup(pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNewPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pChangePasswordLayout.createSequentialGroup()
                        .addComponent(bChangePasswordYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bChangePasswordNo)))
                .addContainerGap())
        );
        pChangePasswordLayout.setVerticalGroup(
            pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pChangePasswordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOldPassword)
                    .addComponent(lNewPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bChangePasswordYes)
                    .addComponent(bChangePasswordNo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bChangePasswordYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangePasswordYesActionPerformed
        this.pChangePassword.setVisible(false);
    }//GEN-LAST:event_bChangePasswordYesActionPerformed

    private void bChangePasswordNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangePasswordNoActionPerformed
        this.pChangePassword.setVisible(false);
    }//GEN-LAST:event_bChangePasswordNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChangePasswordNo;
    private javax.swing.JButton bChangePasswordYes;
    private javax.swing.JLabel lNewPassword;
    private javax.swing.JLabel lOldPassword;
    private javax.swing.JPanel pChangePassword;
    private javax.swing.JPasswordField pfNewPassword;
    private javax.swing.JPasswordField pfOldPassword;
    // End of variables declaration//GEN-END:variables
}
